Fixing metric computation for old vs new ranks with ties
salesforce/ml4ir pull request #243
Opened 2023-07-04 23:57 UTC by lastmansleeping

2023-07-13 19:24 UTC, mohazahran requested changes
left a minor comment.

2023-07-13 20:01 UTC, lastmansleeping commented on python/ml4ir/applications/ranking/model/metrics/helpers/metrics_helper.py
> +    df_clicked = df[df[RankingConstants.PROXY_CLICK] == 1.0]
Sorry, missed this. Can you explain what you mean? I don't get it.

2023-07-14 17:58 UTC, mohazahran commented on python/ml4ir/applications/ranking/model/ranking_model.py
> +            try:
as discussed in slack, there is an option to keep queries with no signals, so these queries would get a proxy click and may disturb the metrics and should be removed. I'm mainly bringing this up as the removed function to get the top graded relevance record used to filter out these queries.

2023-07-14 17:58 UTC, mohazahran commented on python/ml4ir/applications/ranking/model/metrics/helpers/metrics_helper.py
> +    df_clicked = df[df[RankingConstants.PROXY_CLICK] == 1.0]
s discussed in slack, there is an option to keep queries with no signals, so these queries would get a proxy click and may disturb the metrics and should be removed. I'm mainly bringing this up as the removed function to get the top graded relevance record used to filter out these queries.

2023-08-03 18:56 UTC, mohazahran approved these changes
looks good.

2023-08-03 21:23 UTC, merged